'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class StringTemplates
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("StringTemplates", GetType(StringTemplates).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;html xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;
        '''xmlns:x=&quot;urn:schemas-microsoft-com:office:excel&quot;
        '''xmlns=&quot;http://www.w3.org/TR/REC-html40&quot;&gt;
        '''
        '''&lt;head&gt;
        '''&lt;meta http-equiv=Content-Type content=&quot;text/html; charset=windows-1252&quot;&gt;
        '''&lt;meta name=ProgId content=Abovo Model Output&gt;
        '''&lt;meta name=Generator content=&quot;abovo-summit&quot;&gt;
        '''&lt;style id=&quot;XL_Styles&quot;&gt;
        '''&lt;!--table
        '''	{mso-displayed-decimal-separator:&quot;\.&quot;;
        '''	mso-displayed-thousand-separator:&quot;\,&quot;;}
        '''.xl812235
        '''	{table-layout: auto !important;
        '''              padding-t [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property HTMLFinanceTableHeader() As String
            Get
                Return ResourceManager.GetString("HTMLFinanceTableHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;div id=XL align=center x:publishsource=&quot;abovo-summit&quot;&gt;
        '''
        '''&lt;table border=0 cellpadding=0 cellspacing=0 class=xl812235
        ''' style=&apos;border-collapse:collapse;&gt;
        ''' &lt;col class=xl832235&gt;
        ''' &lt;col class=xl812235&gt;
        ''' &lt;col class=xl842235 span=20 style=&apos;mso-width-source:userset;
        '''&apos;&gt;
        ''' &lt;col class=xl842235 style=&apos;mso-width-source:userset;&apos;&gt;
        ''' &lt;col class=xl842235 span=19 style=&apos;mso-width-source:userset;
        '''&gt;.
        '''</summary>
        Friend Shared ReadOnly Property HTMLFinanceTablePrecursor() As String
            Get
                Return ResourceManager.GetString("HTMLFinanceTablePrecursor", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
