Imports System.IO
Imports System.IO.Compression
Imports System.Linq
Imports System.Xml
Imports System.Xml.Linq
Imports DevExpress.Spreadsheet

Namespace Abovo
    '25.2.4 retains XLSB cell-metadata indices but can omit their metadata part
    'during XLSM export. Only the verified single-XLDAPR binary profile is
    'bridged here. Unknown profiles fail closed; worksheet/formula bytes are
    'never rewritten. The XML counterpart is generated by the public API.
    Friend NotInheritable Class RecoveryXlsmCompatibility
        Private Const VerifiedBinaryProfile As String = "zAIAzgIEAQAAAM8CGLDAatjA1AEABgAAAFgATABEAEEAUABSANACANMCFAEAAAAGAAAAWABMAEQAQQBQAFIANAAjBAIAAgCAIACBIAIBACQANQDUAgDRAggBAAAAAQAAADMMAQAAAAEAAAAAAAAA0gIAzQIA"
        Private Shared ReadOnly SpreadsheetNs As String = "http://schemas.openxmlformats.org/spreadsheetml/2006/main"
        Private Shared ReadOnly MetadataRelation As String = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/sheetMetadata"
        Private Shared ReadOnly XmlMetadata As New Lazy(Of Byte())(AddressOf CreateMetadata)

        Friend Shared Function HasVerifiedBinaryProfile(path As String) As Boolean
            Try
                Using package = ZipFile.OpenRead(path)
                    Dim part = package.GetEntry("xl/metadata.bin")
                    If part Is Nothing OrElse part.Length <> 117 Then Return False
                    Using content = part.Open(), buffer As New MemoryStream()
                        content.CopyTo(buffer)
                        Return Convert.ToBase64String(buffer.ToArray()) = VerifiedBinaryProfile
                    End Using
                End Using
            Catch ex As Exception When TypeOf ex Is IOException OrElse TypeOf ex Is UnauthorizedAccessException
                'Legacy/encrypted formats need not be ZIP packages. Reading an
                'optional recovery capability must not prevent ordinary open.
                Abovo.SummitDiagnostics.WriteLine("[Recovery] Optional binary metadata capability unavailable: " & ex.Message)
                Return False
            End Try
        End Function

        Private Shared Function CreateMetadata() As Byte()
            Using sample As New Workbook(), buffer As New MemoryStream()
                sample.Options.CalculationMode = WorkbookCalculationMode.Manual
                sample.Worksheets(0).Cells("A1").DynamicArrayFormulaInvariant = "=SEQUENCE(1)"
                sample.SaveDocument(buffer, DocumentFormat.Xlsm)
                buffer.Position = 0
                Using package As New ZipArchive(buffer, ZipArchiveMode.Read, True), result As New MemoryStream()
                    Using content = package.GetEntry("xl/metadata.xml").Open()
                        content.CopyTo(result)
                    End Using
                    Return result.ToArray()
                End Using
            End Using
        End Function

        Private Shared Function Reader(content As Stream) As XmlReader
            Return XmlReader.Create(content, New XmlReaderSettings With {.DtdProcessing = DtdProcessing.Prohibit,
                .XmlResolver = Nothing, .MaxCharactersInDocument = 536870912})
        End Function

        Private Shared Sub Put(package As ZipArchive, name As String, document As XDocument)
            Dim previous = package.GetEntry(name)
            If previous IsNot Nothing Then previous.Delete()
            Using content = package.CreateEntry(name).Open()
                document.Save(content)
            End Using
        End Sub

        Friend Shared Sub Prepare(filePath As String, verifiedBinaryProfile As Boolean)
            'Opening worksheet entries in Update mode turns the read-only scan
            'into an expensive decompress/recompress pass. Hold one exclusive
            'file handle throughout validation and update, but open the large
            'worksheet parts only in Read mode. Rejected/no-op files stay intact.
            Using file As New FileStream(filePath, FileMode.Open, FileAccess.ReadWrite, FileShare.None)
                Dim relations As XDocument, types As XDocument
                Using package As New ZipArchive(file, ZipArchiveMode.Read, True)
                    If package.GetEntry("xl/metadata.xml") IsNot Nothing Then Return
                    Dim hasMetadataCells As Boolean = False
                    For Each part In package.Entries
                        If Not part.FullName.StartsWith("xl/worksheets/", StringComparison.Ordinal) OrElse
                           Not part.FullName.EndsWith(".xml", StringComparison.OrdinalIgnoreCase) Then Continue For
                        Using content = part.Open(), xml = Reader(content)
                            While xml.Read()
                                If xml.NodeType <> XmlNodeType.Element OrElse xml.LocalName <> "c" OrElse xml.NamespaceURI <> SpreadsheetNs Then Continue While
                                Dim cm = xml.GetAttribute("cm"), vm = xml.GetAttribute("vm")
                                If vm IsNot Nothing OrElse (cm IsNot Nothing AndAlso cm <> "1") Then
                                    Throw New InvalidDataException("Recovery XLSM export contains an unsupported missing metadata profile; the previous recovery is retained.")
                                End If
                                hasMetadataCells = hasMetadataCells OrElse cm IsNot Nothing
                            End While
                        End Using
                    Next
                    If Not hasMetadataCells Then Return
                    If Not verifiedBinaryProfile Then Throw New InvalidDataException("Recovery XLSM needs a verified dynamic-array metadata conversion for this workbook; the previous recovery is retained.")
                    Using content = package.GetEntry("xl/_rels/workbook.xml.rels").Open(), xml = Reader(content)
                        relations = XDocument.Load(xml)
                    End Using
                    If relations.Root.Elements().Any(Function(e) CStr(e.Attribute("Type")) = MetadataRelation) Then Throw New InvalidDataException("Recovery metadata relationship exists without its part.")
                    Using content = package.GetEntry("[Content_Types].xml").Open(), xml = Reader(content)
                        types = XDocument.Load(xml)
                    End Using
                    If types.Root.Elements().Any(Function(e) CStr(e.Attribute("PartName")) = "/xl/metadata.xml") Then Throw New InvalidDataException("Recovery metadata content type exists without its part.")
                End Using
                Dim bytes = XmlMetadata.Value
                file.Position = 0
                Using package As New ZipArchive(file, ZipArchiveMode.Update, True)
                    Using content = package.CreateEntry("xl/metadata.xml").Open()
                        content.Write(bytes, 0, bytes.Length)
                    End Using
                    relations.Root.Add(New XElement(relations.Root.Name.Namespace + "Relationship", New XAttribute("Id", "rIdRecoveryMetadata" & Guid.NewGuid().ToString("N")),
                        New XAttribute("Type", MetadataRelation), New XAttribute("Target", "metadata.xml")))
                    types.Root.Add(New XElement(types.Root.Name.Namespace + "Override", New XAttribute("PartName", "/xl/metadata.xml"),
                        New XAttribute("ContentType", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheetMetadata+xml")))
                    Put(package, "xl/_rels/workbook.xml.rels", relations)
                    Put(package, "[Content_Types].xml", types)
                End Using
                Abovo.SummitDiagnostics.WriteLine("[Recovery] Preserved verified XLSB dynamic-array metadata in XLSM.")
            End Using
        End Sub
    End Class
End Namespace
