<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Exe</OutputType>
    <LangVersion>7.3</LangVersion>
    <PlatformTarget>x64</PlatformTarget>
    <OutputPath>bin/$(PlatformTarget)/$(Configuration)/</OutputPath>
    <IntermediateOutputPath>obj/$(PlatformTarget)/$(Configuration)/</IntermediateOutputPath>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
    <DefineConstants>$(DefineConstants);SPREAD_TRIAL;TRIAL_X64</DefineConstants>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <RestorePackagesPath>$(MSBuildThisFileDirectory)../../packages/spread-trial</RestorePackagesPath>
    <NuGetAudit>true</NuGetAudit>
    <NuGetAuditMode>all</NuGetAuditMode>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Mescius.Spreadsheet.Core" Version="[19.2.0]" />
    <PackageReference Include="GrapeCity.Spread.WinForms" Version="[19.2.0]" />
    <PackageReference Include="Aspose.Cells" Version="[26.9.0]" />
    <PackageReference Include="SpreadsheetGear" Version="[9.3.85]" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Web.Extensions" />
    <Reference Include="System.Security" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.IO.Compression.FileSystem" />
    <Reference Include="DevExpress.Docs.v25.2"><HintPath>../../bin/Release/DevExpress.Docs.v25.2.dll</HintPath></Reference>
    <Reference Include="DevExpress.Spreadsheet.v25.2.Core"><HintPath>../../bin/Release/DevExpress.Spreadsheet.v25.2.Core.dll</HintPath></Reference>
    <Reference Include="DevExpress.Data.v25.2"><HintPath>../../bin/Release/DevExpress.Data.v25.2.dll</HintPath></Reference>
    <Reference Include="DevExpress.Office.v25.2.Core"><HintPath>../../bin/Release/DevExpress.Office.v25.2.Core.dll</HintPath></Reference>
    <Reference Include="DevExpress.Drawing.v25.2"><HintPath>../../bin/Release/DevExpress.Drawing.v25.2.dll</HintPath></Reference>
    <Reference Include="DevExpress.Printing.v25.2.Core"><HintPath>../../bin/Release/DevExpress.Printing.v25.2.Core.dll</HintPath></Reference>
    <Compile Include="../SpreadsheetEngineTrial/EngineBenchmark.cs" Link="Shared/EngineBenchmark.cs" />
    <Compile Include="../SpreadsheetEngineTrial/TrialFunctions.cs" Link="Shared/TrialFunctions.cs" />
    <Compile Include="../SpreadsheetEngineTrial/TrialProtection.cs" Link="Shared/TrialProtection.cs" />
    <Compile Include="../SpreadsheetEngineTrial/SpreadsheetGearTrial.cs" Link="Shared/SpreadsheetGearTrial.cs" />
    <Compile Include="../SpreadsheetEngineTrial/IoTrial.cs" Link="Shared/IoTrial.cs" />
  </ItemGroup>
</Project>
