Option Strict On

Imports System.IO
Imports System.Security.Cryptography
Imports System.Text
Imports System.Threading
Imports System.Xml.Linq
Imports Abovo.WorkbookEngines

Namespace Abovo
    ' Immutable display-history evidence, never an executable Undo stack or a
    ' proof that the engine contains every live UI edit. It cannot clear dirty.
    Public NotInheritable Class ModelHistorySnapshot
        Public ReadOnly Property Id As Guid = Guid.NewGuid()
        Public ReadOnly Property ManagerId As Guid
        Public ReadOnly Property SessionId As Guid
        Public ReadOnly Property EngineRevision As Long
        Public ReadOnly Property SourceHash As String
        Public ReadOnly Property SourcePath As String
        Public ReadOnly Property UserRevision As Long
        Public ReadOnly Property CalculationRevision As Long
        Public ReadOnly Property Hash As String
        Private ReadOnly xml As String

        Friend Sub New(managerId As Guid, sourcePath As String, userRevision As Long, calculationRevision As Long,
                       expected As WorkbookCalculationResult, document As XDocument)
            Me.ManagerId = managerId : Me.SourcePath = IO.Path.GetFullPath(sourcePath)
            Me.UserRevision = userRevision : Me.CalculationRevision = calculationRevision
            SessionId = expected.SessionId : EngineRevision = expected.Revision : SourceHash = expected.SourceHash
            xml = document.ToString(SaveOptions.DisableFormatting)
            If Encoding.UTF8.GetByteCount(xml) > 16000000 Then Throw New InvalidDataException("Saved history exceeds the 16 MB limit.")
            Hash = Digest(xml)
        End Sub

        Friend Function Document() As XDocument
            ' Text was generated by the existing bounded history serializer, not
            ' received as arbitrary XML from a workbook or external process.
            Return XDocument.Parse(xml, LoadOptions.PreserveWhitespace)
        End Function

        Friend Shared Function Digest(value As String) As String
            Using algorithm = SHA256.Create()
                Return BitConverter.ToString(algorithm.ComputeHash(Encoding.UTF8.GetBytes(value))).Replace("-", "")
            End Using
        End Function
    End Class

    Partial Public NotInheritable Class ModelChangeManagerV2
        Private ReadOnly saveHistoryIdentity As Guid = Guid.NewGuid()
        Private ReadOnly saveHistoryOwnerThread As Integer = Thread.CurrentThread.ManagedThreadId

        Private Function RequireSaveHistoryOwner() As FileManager.ExcelModel
            If Thread.CurrentThread.ManagedThreadId <> saveHistoryOwnerThread Then Throw New InvalidOperationException("Capture/check history on the change manager's owning thread.")
            If FileManager.ExcelModels Is Nothing OrElse ModelID < 0 OrElse ModelID >= FileManager.ExcelModels.Length Then Throw New InvalidOperationException("The model is no longer open.")
            Dim model = FileManager.ExcelModels(ModelID)
            If model Is Nothing OrElse model.IsClosing OrElse Not Object.ReferenceEquals(model.ChangeManager, Me) OrElse
                Not Object.ReferenceEquals(model.WB, WB) OrElse ChangeInProgress OrElse
                ModelSafetyManager.IsBulkWorkbookMutationInProgress(ModelID) Then Throw New InvalidOperationException("The model is unavailable or a change is still in progress.")
            Return model
        End Function

        Public Function CaptureSaveHistory(expected As WorkbookCalculationResult) As ModelHistorySnapshot
            If expected Is Nothing Then Throw New ArgumentNullException(NameOf(expected))
            Dim model = RequireSaveHistoryOwner()
            Dim path = IO.Path.GetFullPath(model.FileName)
            Using input As New FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read), algorithm = SHA256.Create()
                If BitConverter.ToString(algorithm.ComputeHash(input)).Replace("-", "") <> expected.SourceHash Then Throw New IOException("History and calculation do not share the same opening workbook.")
            End Using
            Return New ModelHistorySnapshot(saveHistoryIdentity, path, model.UserChangeRevision, model.CalculationRevision,
                                            expected, RecoveryHistoryStore.ToDocument(GetHistoryTable()))
        End Function

        ' Necessary evidence for a future exact-revision acknowledgement, NOT
        ' an acknowledgement itself. Value/format ownership and current model
        ' XML still need integration before a caller may mark the model clean.
        Public Function IsSavedHistoryCurrent(snapshot As ModelHistorySnapshot, receipt As WorkbookPublicationReceipt) As Boolean
            Dim model = RequireSaveHistoryOwner()
            Return IsSavedHistoryCurrentCore(model, snapshot, receipt)
        End Function

        Private Function IsSavedHistoryCurrentCore(model As FileManager.ExcelModel, snapshot As ModelHistorySnapshot,
                                                   receipt As WorkbookPublicationReceipt) As Boolean
            Return snapshot IsNot Nothing AndAlso receipt IsNot Nothing AndAlso snapshot.ManagerId = saveHistoryIdentity AndAlso
                receipt.HistorySnapshotId = snapshot.Id AndAlso receipt.HistoryHash = snapshot.Hash AndAlso
                receipt.SessionId = snapshot.SessionId AndAlso receipt.Revision = snapshot.EngineRevision AndAlso
                model.UserChangeRevision = snapshot.UserRevision AndAlso model.CalculationRevision = snapshot.CalculationRevision AndAlso
                String.Equals(IO.Path.GetFullPath(model.FileName), snapshot.SourcePath, StringComparison.OrdinalIgnoreCase) AndAlso
                ModelHistorySnapshot.Digest(RecoveryHistoryStore.ToDocument(GetHistoryTable()).ToString(SaveOptions.DisableFormatting)) = snapshot.Hash
        End Function
    End Class
End Namespace
